#服务端口
server.port: 8080

#服务运行于反向代理后，且用context-path作为流量区分时，增加此配置
#server.servlet.context-path: /comicbank

management:
  server.port: 8081
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.health.show-details: never
  health:
    defaults.enabled: false
    db.enabled: false
  info.git.mode: full


spring:
  main:
    banner-mode: "OFF"
  application.name: ComicBank
  boot.admin.client:
    enabled: false
    url: http://localhost:25020
    instance.prefer-ip: true
    auto-deregistration: true

logging:
  file: logs/comicbank.log
  file.max-history: 30
  level:
    root: info
    com.lvt4j.mangabank: info

#cwebp命令的路径
cwebp.path: cwebp

#临时文件夹路径
tmp.dir: tmp

#数据文件夹路径
data.dir: data

#存放漫画的文件夹
book.dir: ${data.dir}/book

#本程序存放各种元数据的文件夹
meta.dir: ${data.dir}/meta
lucene.id.dir: ${meta.dir}/id
lucene.book.dir: ${meta.dir}/book
lucene.user.dir: ${meta.dir}/user
lucene.tag.dir: ${meta.dir}/tag
lucene.imgCache.dir: ${meta.dir}/imgCache